language: python
python:
  - 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc openjdk-7-jre
  #- sudo apt-get install aspell aspell-en aspell-ru
  - curl -O https://languagetool.org/download/LanguageTool-2.7.zip && unzip LanguageTool-2.7.zip -d ~

install:
  - pip install requests markdown beautifulsoup4
  # JavaScript test requirements
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install yaspeller -g

script:
  #- python w3c-validator.py http://blog.bronevichok.ru
  - python mft.py http://blog.bronevichok.ru
  #- python check_urls.py _posts/*.md
  # Language Tool
  #- java -jar ~/LanguageTool-2.7/languagetool-commandline.jar --autoDetect _posts/*.md
  # Yaspeller
  - yaspeller .
  #- find . -name "*.md" -exec aspell --lang=en --mode=tex check "{}" \;

notifications:
  email: false
