# Site settings
title:       Сергей Бронников
email:       estetus@gmail.com
author:      Sergey Bronnikov
description: "блог о тестировании, продуктивности"
baseurl:     ""
url:         "http://blog.bronevichok.ru/"

# Google analytics
google_analytics: UA-47888478-2

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    date
paginate:     3
sass:
  compressed: true
