baseurl = "https://bronevichok.ru/blog/"
#baseurl = "."
languagecode = "en-us"
title = "Сергей Бронников"
theme = "hugo-zen"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
uglyurls = true
disablePathToLower = true
MetaDataFormat = "toml"
copyright = "Сергей Бронников, 2014-2017"
rssuri = "atom.xml"
[indexes]
	category = "categories"
	tag = "tags"
[author]
	name = "Сергей Бронников"
[permalinks]
	posts = "/:year/:month/:day/:filename/"
	books = "/:year/:month/:day/:filename/"
[params]
	logo      = "/images/logo.jpg"
	analytics = "UA-47888478-2"
